// Applies SQL migrations from ./drizzle (generated by drizzle-kit).
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db, pool } from './client.js';

async function main() {
  console.log('[db] running migrations...');
  await migrate(db, { migrationsFolder: new URL('../../drizzle', import.meta.url).pathname });
  console.log('[db] migrations complete');
  await pool.end();
}

main().catch((err) => {
  console.error('[db] migration failed:', err);
  process.exit(1);
});
